apiVersion: app.fybrik.io/v1beta1
kind: FybrikModule
metadata:
  name: trino-module
  labels:
    name: trino-module
    version: 0.0.1  # semantic version
  namespace: fybrik-system
spec:
  type: service
  chart:
    name: ghcr.io/fybrik/trino-module-chart:0.3.0
    values:
      imageChart.tag: 0.3.0
  capabilities:
    - capability: read
      scope: workload
      api:
        connection:
          name: rest
          rest:
            endpoint: "https://{{ .Release.Name }}.{{ .Release.Namespace }}:80/readAsset"
      supportedInterfaces:
        - source:
            protocol: s3
            dataformat: iceberg
        - source:
            protocol: s3
            dataformat: csv
      actions:
        - name: RedactAction
        - name: RemoveAction
